name: Meto OS Final Build V9

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Unzip Source Code
      run: unzip MetoOS-Project-Files.zip -d build_root
      
    - name: Debug: List contents of extracted folder
      run: ls -R build_root
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x build_root/MetoOS-Project-Files/gradlew

    - name: Run Build
      run: cd build_root/MetoOS-Project-Files && ./gradlew assembleDebug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: MetoOS-Ready-APK
        path: build_root/MetoOS-Project-Files/app/build/outputs/apk/debug/app-debug.apk 
